### ISSUE TITLE
pod好像有问题

### ISSUE THREAD

**Issue by a442914168** [iphone5solo/Gank#1]
我install 之后有几个地方 有错哦
1、
[loadFailView refreshWhenNwrworkError:^(JHUD *hud) {
            [weakSelf.webView loadRequest:self.request];
        }];

2、
    sideMenuController.delegate = contentViewController;

注释掉之后允许PYResource这个类的
 CGSize titleSize = [titleText sizeWithMaxWidth:[UIScreen mainScreen].bounds.size.width -40 -20 font:[UIFont preferredFontForTextStyle:UIFontTextStyleTitle3]];
闪退。。

**Comment by iphone5solo** [comment]
@a442914168 谢谢反馈，现在及时修复了，欢迎下载测试！
